unihelp/web/djangoproject/djangoproject/urls.py
from django.conf.urls import include, url
from django.contrib import admin


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('unihelp.urls')),
]

unihelp/web/djangoproject/unihelp/urls.py
from django.conf.urls import include, url
from django.contrib.auth.views import logout
from . import views


app_name = "unihelp"

users_patterns = [
    url(r'^$', views.users, name='users'),
    url(r'^login/$', views.login, name='login'),
    url(r'^logout/$', logout, {'next_page': 'unihelp:home'}, name='logout'),
    url(r'^signup/$', views.signup, name='signup'),
    url(r'^send/(?P<user_id>[0-9]+)/$', views.send_notification, name='send_notification'),
    url(r'^delete/(?P<user_id>[0-9]+)/$', views.delete_user, name='delete_user')
]


tags_patterns = [
    url(r'^$', views.tags, name='tags'),
    url(r'^new/$', views.create_tag, name='new_tag'),
    url(r'^edit/(?P<tag_id>[0-9]+)/$', views.edit_tag, name='edit_tag'),
    url(r'^delete/(?P<tag_id>[0-9]+)/$', views.delete_tag, name='delete_tag'),
]


planners_patterns = [
    url(r'^repeats/$', views.repeats, name='repeats'),
    url(r'^repeats/new$', views.create_repeat_task, name='new_repeat'),
    url(r'^$', views.planners, name='planners'),
    url(r'^new/$', views.create_planner, name='new_planner'),
    url(r'^edit/(?P<planner_id>[0-9]+)/$', views.edit_planner, name='edit_planner'),
    url(r'^delete/(?P<planner_id>[0-9]+)/$', views.delete_planner, name='delete_planner'),
]


notifications_patterns = [
    url(r'^$', views.notifications, name='notifications'),
    url(r'^new/$', views.create_notification, name='new_notification'),
    url(r'^all/$', views.search_all_notifications, name='all_notifications'),
    url(r'^created/$', views.search_created_notifications, name='created_notifications'),
    url(r'^await/$', views.search_await_notifications, name='await_notifications'),
    url(r'^shown/$', views.search_shown_notifications, name='shown_notifications'),
    url(r'^edit/(?P<notification_id>[0-9]+)/$', views.edit_notification, name='edit_notification'),
    url(r'^delete/(?P<notification_id>[0-9]+)/$', views.delete_notification, name='delete_notification'),
    url(r'^set_shown/(?P<notification_id>[0-9]+)/$', views.set_shown_notification, name='set_shown_notification'),
]


tasks_patterns = [
    url(r'^$', views.search_active_tasks, name='tasks'),
    url(r'^new/$', views.create_task, name='new_task'),
    url(r'^subtask/(?P<parent_id>[0-9]+)/$', views.add_subtask, name='add_subtask'),
    url(r'^(?P<task_id>[0-9]+)/$', views.show_task, name='show_task'),
    url(r'^edit/(?P<task_id>[0-9]+)/$', views.edit_task, name='edit_task'),
    url(r'^update/(?P<task_id>[0-9]+)/$', views.update_task, name='update_task'),
    url(r'^delete/(?P<task_id>[0-9]+)/$', views.delete_task, name='delete_task'),
    url(r'^delete_archived/(?P<task_id>[0-9]+)/$', views.delete_archived_task, name='delete_archived_task'),
    url(r'^subtask/$', views.user_tasks, name='user_tasks'),
    url(r'^can_read/$', views.search_can_read_tasks, name='can_read_tasks'),
    url(r'^can_write/$', views.search_can_write_tasks, name='can_write_tasks'),
    url(r'^tag/(?P<tag_id>[0-9]+)/$', views.search_tasks_by_tag, name='tasks_by_tag'),
    url(r'^status/(?P<status_value>[0-9]+)/$', views.search_tasks_by_status, name='tasks_by_status'),
    url(r'^priority/(?P<priority_value>[0-9]+)/$', views.search_tasks_by_priority, name='tasks_by_priority'),
    url(r'^planner/(?P<planner_id>[0-9]+)/$', views.search_tasks_by_planner, name='tasks_by_planner'),
]


urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^users/', include(users_patterns)),
    url(r'^tags/', include(tags_patterns)),
    url(r'^tasks/', include(tasks_patterns)),
    url(r'^notifications/', include(notifications_patterns)),
    url(r'^planners/', include(planners_patterns))
]

unihelp/web/djangoproject/templates/notifications/edit.html
{% extends 'base.html' %}

{% block title %}Edit notification{% endblock %}

{% block content %}
{% load bootstrap4 %}

<h2>Edit notification</h2>
<form method="post">
  {% csrf_token %}
  {% bootstrap_form form %}
  {% buttons %}
    <button type="submit" class="btn btn-success">Update</button>
  {% endbuttons %}
</form>
<input class='btn btn-primary' type=button value="Back" onClick="javascript:history.go(-1);">

{% endblock %}

unihelp/web/djangoproject/templates/notifications/index.html
{% extends 'base.html' %}
{% block title %}Notifications{% endblock %}

{% block content %}
{% load template_tags %}

<h2>Notifications</h2>
<div class='table-responsive' id='table'>
  <div class="input-group col-md-3" style='padding-left: 0'>
    <input class="form-control search" placeholder="Search...">
    <span class="input-group-append">
      <button class="btn btn-outline-secondary" type="button">
        <i class="fa fa-search"></i>
      </button>
    </span>
  </div>
  <table class="table table-hover" style="width: inherit;">
    <thead>
      <tr>
        <th class="sort" data-sort="id">ID</th>
        <th class="sort" data-sort="title">Title</th>
        <th class="sort" data-sort="work_start_time">Work start time</th>
        <th class="sort" data-sort="state">State</th>
        <th class="sort" data-sort="task">Task</th>
        <th>Action</th>
      </tr>
    </thead>
    <tbody class="list">
      {% for notification in notifications %}
      <tr>
        <td class="id" scope="row">{{notification.id}}</td>
        <td class="title">{{notification.title}}</td>
        <td class="work_start_time">{{notification.work_start_time}}</td>
        <td class="state">
          <h5><span class="badge badge-{% get_state_tag notification.state %}">{% get_state notification.state %}</span></h5>
        </td>
        <td class="task">
          {% if notification.task_id is not None %}
            <a href="{% url 'unihelp:show_task' notification.task_id %}">
              {% get_task_title notification.user_id notification.task_id %}
            </a>
          {% endif %}
        </td>
        <td>
          {% if view == 'await' %}
          <form style='display: inline-block;' action="{% url 'unihelp:set_shown_notification' notification.id %}" method='post'>
            {% csrf_token %}
            <button type='submit' class='btn btn-primary'>Set as shown</button>
          </form>
          {% endif %}
          <a href="{% url 'unihelp:edit_notification' notification.id %}" class='btn btn-warning'>Edit</a>
          <form style='display: inline-block;' action="{% url 'unihelp:delete_notification' notification.id %}" method='post'>
            {% csrf_token %}
            <button type='submit' class='btn btn-danger' onclick="return confirm('Are you sure you want to delete this notification?')">Delete</button>
          </form>
        </td>
      </tr>
    {% endfor %}
    </tbody>
  </table>
  <ul class='pagination'></ul>
</div>
<a href="{% url 'unihelp:new_notification' %}" class='btn btn-outline-dark'>Add notification</a>
<script>
var options = {
  valueNames: [ 'id', 'title', 'work_start_time', {
    name: 'state',
    attr: 'value'
  }, 'task' ],
  pagination: true,
  page: 7,
};
var list = new List('table', options);
if(list.size() / list.page <= 1){
  document.getElementsByClassName('pagination')[0].style.display = 'none';
}
</script>
{% endblock %}

unihelp/web/djangoproject/templates/notifications/new.html
{% extends 'base.html' %}

{% block title %}New notification{% endblock %}

{% block content %}
{% load bootstrap4 %}
{{ form.media }}

<h2>New notification</h2>
<div class='form' style="position: relative">
  <form method="post">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons %}
      <button type="submit" class="btn btn-dark">Accept</button>
    {% endbuttons %}
  </form>
</div>
<input class='btn btn-outline-dark' type=button value="Back" onClick="javascript:history.go(-1);">
{% endblock %}