unihelp/web/djangoproject/djangoproject/urls.py
from django.conf.urls import include, url
from django.contrib import admin


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('unihelp.urls')),
]

unihelp/web/djangoproject/unihelp/urls.py
from django.conf.urls import include, url
from django.contrib.auth.views import logout
from . import views


app_name = "unihelp"

users_patterns = [
    url(r'^$', views.users, name='users'),
    url(r'^login/$', views.login, name='login'),
    url(r'^logout/$', logout, {'next_page': 'unihelp:home'}, name='logout'),
    url(r'^signup/$', views.signup, name='signup'),
    url(r'^send/(?P<user_id>[0-9]+)/$', views.send_notification, name='send_notification'),
    url(r'^delete/(?P<user_id>[0-9]+)/$', views.delete_user, name='delete_user')
]


tags_patterns = [
    url(r'^$', views.tags, name='tags'),
    url(r'^new/$', views.create_tag, name='new_tag'),
    url(r'^edit/(?P<tag_id>[0-9]+)/$', views.edit_tag, name='edit_tag'),
    url(r'^delete/(?P<tag_id>[0-9]+)/$', views.delete_tag, name='delete_tag'),
]


planners_patterns = [
    url(r'^repeats/$', views.repeats, name='repeats'),
    url(r'^repeats/new$', views.create_repeat_task, name='new_repeat'),
    url(r'^$', views.planners, name='planners'),
    url(r'^new/$', views.create_planner, name='new_planner'),
    url(r'^edit/(?P<planner_id>[0-9]+)/$', views.edit_planner, name='edit_planner'),
    url(r'^delete/(?P<planner_id>[0-9]+)/$', views.delete_planner, name='delete_planner'),
]


notifications_patterns = [
    url(r'^$', views.notifications, name='notifications'),
    url(r'^new/$', views.create_notification, name='new_notification'),
    url(r'^all/$', views.search_all_notifications, name='all_notifications'),
    url(r'^created/$', views.search_created_notifications, name='created_notifications'),
    url(r'^await/$', views.search_await_notifications, name='await_notifications'),
    url(r'^shown/$', views.search_shown_notifications, name='shown_notifications'),
    url(r'^edit/(?P<notification_id>[0-9]+)/$', views.edit_notification, name='edit_notification'),
    url(r'^delete/(?P<notification_id>[0-9]+)/$', views.delete_notification, name='delete_notification'),
    url(r'^set_shown/(?P<notification_id>[0-9]+)/$', views.set_shown_notification, name='set_shown_notification'),
]


tasks_patterns = [
    url(r'^$', views.search_active_tasks, name='tasks'),
    url(r'^new/$', views.create_task, name='new_task'),
    url(r'^subtask/(?P<parent_id>[0-9]+)/$', views.add_subtask, name='add_subtask'),
    url(r'^(?P<task_id>[0-9]+)/$', views.show_task, name='show_task'),
    url(r'^edit/(?P<task_id>[0-9]+)/$', views.edit_task, name='edit_task'),
    url(r'^update/(?P<task_id>[0-9]+)/$', views.update_task, name='update_task'),
    url(r'^delete/(?P<task_id>[0-9]+)/$', views.delete_task, name='delete_task'),
    url(r'^delete_archived/(?P<task_id>[0-9]+)/$', views.delete_archived_task, name='delete_archived_task'),
    url(r'^subtask/$', views.user_tasks, name='user_tasks'),
    url(r'^can_read/$', views.search_can_read_tasks, name='can_read_tasks'),
    url(r'^can_write/$', views.search_can_write_tasks, name='can_write_tasks'),
    url(r'^tag/(?P<tag_id>[0-9]+)/$', views.search_tasks_by_tag, name='tasks_by_tag'),
    url(r'^status/(?P<status_value>[0-9]+)/$', views.search_tasks_by_status, name='tasks_by_status'),
    url(r'^priority/(?P<priority_value>[0-9]+)/$', views.search_tasks_by_priority, name='tasks_by_priority'),
    url(r'^planner/(?P<planner_id>[0-9]+)/$', views.search_tasks_by_planner, name='tasks_by_planner'),
]


urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^users/', include(users_patterns)),
    url(r'^tags/', include(tags_patterns)),
    url(r'^tasks/', include(tasks_patterns)),
    url(r'^notifications/', include(notifications_patterns)),
    url(r'^planners/', include(planners_patterns))
]

unihelp/web/djangoproject/templates/tasks/edit.html
{% extends 'base.html' %}

{% block title %}Edit task{% endblock %}

{% block content %}
{% load bootstrap4 %}
{{ form.media }}

<h2>Edit task</h2>
<div class='form' style="position: relative">
  <form method="post">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons %}
      <button type="submit" class="btn btn-success">Update</button>
    {% endbuttons %}
  </form>
</div>
<input class='btn btn-primary' type=button value="Back" onClick="javascript:history.go(-1);">
{% endblock %}

unihelp/web/djangoproject/templates/tasks/index.html
{% extends 'base.html' %}
{% block title %}Tasks{% endblock %}
{% block content %}
{% load template_tags %}

<h2>{{header|safe}}</h2>
<div class='table-responsive' id='table'>
    <div class="input-group col-md-3" style='padding-left: 0'>
      <input class="form-control search" placeholder="Search...">
      <span class="input-group-append">
        <button class="btn btn-outline-secondary" type="button">
          <i class="fa fa-search"></i>
        </button>
      </span>
    </div>
    <table class="table table-hover" style="width: inherit;">
    <thead>
      <tr>
        <th class="sort" data-sort="id">ID</th>
        <th class="sort" data-sort="title">Title</th>
        <th class="sort" data-sort="note">Note</th>
        <th class="sort" data-sort="tag">Tag</th>
        <th class="sort" data-sort="status">Status</th>
        <th class="sort" data-sort="priority">Priority</th>
        <th>Action</th>
      </tr>
    </thead>
    <tbody class="list">
      {% for task in tasks %}
      <tr>
        <td class="id" data-toggle="modal" data-id="{{task.id}}" data-title="{{task.title}}" data-target="#modal" data-status="{{task.status}}" data-priority="{{task.priority}}" scope="row">{{task.id}}</td>
        <td class="title" data-toggle="modal" data-id="{{task.id}}" data-title="{{task.title}}" data-target="#modal" data-status="{{task.status}}" data-priority="{{task.priority}}">{{task.title}}</td>
        <td class="note" data-toggle="modal" data-id="{{task.id}}" data-title="{{task.title}}" data-target="#modal" data-status="{{task.status}}" data-priority="{{task.priority}}">{{task.note}}</td>
        <td class="tag">
          {% if foreign_tag %}
            {% search_tag_name user.id task.tag_id %}
          {% elif task.tag_id is not None %}
            <a href="{% url 'unihelp:tasks_by_tag' task.tag_id %}">{% search_tag_name user.id task.tag_id %}</a>
          {% endif %}
        </td>
        <td class="status">
          <h5><a class="badge badge-{% get_status_tag task.status %}" href="{% url 'unihelp:tasks_by_status' task.status %}">{% get_status task.status %}</a></h5>
        </td>
        <td class="priority">
          <h5><a class="badge badge-{% get_priority_tag task.priority %}" href="{% url 'unihelp:tasks_by_priority' task.priority %}">{% get_priority task.priority %}</a></h5>
        </td>
        <td>
          <a href="{% url 'unihelp:show_task' task.id %}" class='btn btn-dark'>Show</a>
          {% if view != 'can_read' %}
            <a href="{% url 'unihelp:edit_task' task.id %}" class='btn btn-warning'>Edit</a>
            {% if task.status != 4 %}
              <form style='display: inline-block;' action="{% url 'unihelp:delete_task' task.id %}" method='post'>
                {% csrf_token %}
                <button type='submit' class='btn btn-danger' onclick="return confirm('Are you sure you want to delete this task?')">Delete</button>
              </form>
            {% else %}
              <form style='display: inline-block;' action="{% url 'unihelp:delete_archived_task' task.id %}" method='post'>
                {% csrf_token %}
                <button type='submit' class='btn btn-danger' onclick="return confirm('Are you sure you want to delete this task?')">Delete</button>
              </form>
            {% endif %}
          {% endif %}
          <a href="{% url 'unihelp:add_subtask' task.id %}" class="btn btn-outline-dark">Add subtask</a>
          </td>
      </tr>
    {% endfor %}
    </tbody>
  </table>
  <ul class='pagination'></ul>
</div>
<a href="{% url 'unihelp:new_task' %}{{query}}" class='btn btn-outline-dark'>Add task</a>
{% if view != 'can_read' and status_id != '4' %}
{% endif %}
<script>
var options = {
  valueNames: [ 'id', 'title', 'note', 'tag', {
    name: 'status',
    attr: 'value'
  }, {
    name: 'priority',
    attr: 'value'
  }],
  pagination: true,
  page: 7,
};
var list = new List('table', options);
if(list.size() / list.page <= 1){
  document.getElementsByClassName('pagination')[0].style.display = 'none';
}
</script>
{% endblock %}

unihelp/web/djangoproject/templates/tasks/new.html
{% extends 'base.html' %}

{% block title %}New task{% endblock %}

{% block content %}
{% load bootstrap4 %}
{{ form.media }}

<h2>New task</h2>
<div class='form'>
  <form method="post">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons %}
      <button type="submit" class="btn btn-dark">Accept</button>
    {% endbuttons %}
  </form>
</div>
<input class='btn btn-outline-dark' type=button value="Back" onClick="javascript:history.go(-1);">
{% endblock %}

unihelp/web/djangoproject/templates/tasks/show.html
{% extends 'base.html' %}

{% block title %}Task info{% endblock %}
{% load template_tags %}
{% block content %}

<h2>Task info</h2>
<table class="table table-striped">
  <tbody>
    <tr>
      <td class="title">ID</td>
      <td>{{task.id}}</td>
    </tr>
    <tr>
      <td class="title">Title</td>
      <td>{{task.title}}</td>
    </tr>
    <tr>
      <td class="title">Note</td>
      <td>{{task.note}}</td>
    </tr>
    <tr>
      <td class="title">Tag</td>
      <td>
        {% if task.tag_id is not None %}
        <a href="{% url 'unihelp:tasks_by_tag' tag.id %}"> {{tag.name}}</a>
        {% else %}
        {{task.tag_id}}
        {% endif %}
      </td>
    </tr>
    <tr>
      <td class="title">Priority</td>
      <td>
        <h5><a class="badge badge-{% get_priority_tag task.priority %}" href="{% url 'unihelp:tasks_by_priority' task.priority %}"> {{priority}}</a></h5>
      </td>
    </tr>
    <tr>
      <td class="title">Status</td>
      <td>
        <h5><a class="badge badge-{% get_status_tag task.status %}" href="{% url 'unihelp:tasks_by_status' task.status %}"> {{status}}</a></h5>
      </td>
    </tr>
    <tr>
      <td class="title">Created at</td>
      <td>{{task.time_create}}</td>
    </tr>
    <tr>
      <td class="title">Updated at</td>
      <td>{{task.time_update}}</td>
    </tr>
    <tr>
      <td class="title">Event</td>
      <td>{{task.is_event}}</td>
    </tr>
    <tr>
      <td class="title">Time start</td>
      <td>{{task.time_start}}</td>
    </tr>
    <tr>
      <td class="title">Time end</td>
      <td>{{task.time_end}}</td>
    </tr>
    <tr>
      <td class="title">Parent task</td>
      <td>
        {% if parent_task_title is not None %}
        <a href="{% url 'unihelp:show_task' task.parent_task_id%}">{{ parent_task_title }}</a>
        {% else %}
        {{ parent_task_title }}
        {% endif %}
      </td>
    </tr>
    <tr>
      <td class="title">Subtasks</td>
      <td>
        {% for subtask in subtasks %}
          <a href="{% url 'unihelp:show_task' subtask.id%}">{{ subtask.title }}</a>{% if not forloop.last %},{% endif %}
        {% endfor %}
      </td>
    </tr>
    <tr>
      <td class="title">Creator</td>
      <td>{{creator}}</td>
    </tr>
  </tbody>
</table>
<input class='btn btn-dark' type=button value="Back" onClick="javascript:history.go(-1);">
<div class='right'>
  <a href="{% url 'unihelp:edit_task' task.id %}" class='btn btn-warning'>Edit</a>
  <form style='display: inline-block;' action="{% url 'unihelp:delete_task' task.id %}" method='post'>
    {% csrf_token %}
    <button type='submit' class='btn btn-danger' onclick="return confirm('Are you sure you want to delete this task?')">Delete</button>
  </form>
</div>
{% endblock %}

unihelp/web/djangoproject/templates/tasks/subtask.html
{% extends 'base.html' %}

{% block title %}New subtask{% endblock %}

{% block content %}
{% load bootstrap4 %}
{{ form.media }}

<h2>New subtask</h2>
<div class='form' style="position: relative">
  <form method="post">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons %}
      <button type="submit" class="btn btn-dark">Accept</button>
    {% endbuttons %}
  </form>
</div>
<input class='btn btn-outline-dark' type=button value="Back" onClick="javascript:history.go(-1);">
{% endblock %}