unihelp/web/djangoproject/djangoproject/urls.py
from django.conf.urls import include, url
from django.contrib import admin


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('unihelp.urls')),
]

unihelp/web/djangoproject/unihelp/urls.py
from django.conf.urls import include, url
from django.contrib.auth.views import logout
from . import views


app_name = "unihelp"

users_patterns = [
    url(r'^$', views.users, name='users'),
    url(r'^login/$', views.login, name='login'),
    url(r'^logout/$', logout, {'next_page': 'unihelp:home'}, name='logout'),
    url(r'^signup/$', views.signup, name='signup'),
    url(r'^send/(?P<user_id>[0-9]+)/$', views.send_notification, name='send_notification'),
    url(r'^delete/(?P<user_id>[0-9]+)/$', views.delete_user, name='delete_user')
]


tags_patterns = [
    url(r'^$', views.tags, name='tags'),
    url(r'^new/$', views.create_tag, name='new_tag'),
    url(r'^edit/(?P<tag_id>[0-9]+)/$', views.edit_tag, name='edit_tag'),
    url(r'^delete/(?P<tag_id>[0-9]+)/$', views.delete_tag, name='delete_tag'),
]


planners_patterns = [
    url(r'^repeats/$', views.repeats, name='repeats'),
    url(r'^repeats/new$', views.create_repeat_task, name='new_repeat'),
    url(r'^$', views.planners, name='planners'),
    url(r'^new/$', views.create_planner, name='new_planner'),
    url(r'^edit/(?P<planner_id>[0-9]+)/$', views.edit_planner, name='edit_planner'),
    url(r'^delete/(?P<planner_id>[0-9]+)/$', views.delete_planner, name='delete_planner'),
]


notifications_patterns = [
    url(r'^$', views.notifications, name='notifications'),
    url(r'^new/$', views.create_notification, name='new_notification'),
    url(r'^all/$', views.search_all_notifications, name='all_notifications'),
    url(r'^created/$', views.search_created_notifications, name='created_notifications'),
    url(r'^await/$', views.search_await_notifications, name='await_notifications'),
    url(r'^shown/$', views.search_shown_notifications, name='shown_notifications'),
    url(r'^edit/(?P<notification_id>[0-9]+)/$', views.edit_notification, name='edit_notification'),
    url(r'^delete/(?P<notification_id>[0-9]+)/$', views.delete_notification, name='delete_notification'),
    url(r'^set_shown/(?P<notification_id>[0-9]+)/$', views.set_shown_notification, name='set_shown_notification'),
]


tasks_patterns = [
    url(r'^$', views.search_active_tasks, name='tasks'),
    url(r'^new/$', views.create_task, name='new_task'),
    url(r'^subtask/(?P<parent_id>[0-9]+)/$', views.add_subtask, name='add_subtask'),
    url(r'^(?P<task_id>[0-9]+)/$', views.show_task, name='show_task'),
    url(r'^edit/(?P<task_id>[0-9]+)/$', views.edit_task, name='edit_task'),
    url(r'^update/(?P<task_id>[0-9]+)/$', views.update_task, name='update_task'),
    url(r'^delete/(?P<task_id>[0-9]+)/$', views.delete_task, name='delete_task'),
    url(r'^delete_archived/(?P<task_id>[0-9]+)/$', views.delete_archived_task, name='delete_archived_task'),
    url(r'^subtask/$', views.user_tasks, name='user_tasks'),
    url(r'^can_read/$', views.search_can_read_tasks, name='can_read_tasks'),
    url(r'^can_write/$', views.search_can_write_tasks, name='can_write_tasks'),
    url(r'^tag/(?P<tag_id>[0-9]+)/$', views.search_tasks_by_tag, name='tasks_by_tag'),
    url(r'^status/(?P<status_value>[0-9]+)/$', views.search_tasks_by_status, name='tasks_by_status'),
    url(r'^priority/(?P<priority_value>[0-9]+)/$', views.search_tasks_by_priority, name='tasks_by_priority'),
    url(r'^planner/(?P<planner_id>[0-9]+)/$', views.search_tasks_by_planner, name='tasks_by_planner'),
]


urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^users/', include(users_patterns)),
    url(r'^tags/', include(tags_patterns)),
    url(r'^tasks/', include(tasks_patterns)),
    url(r'^notifications/', include(notifications_patterns)),
    url(r'^planners/', include(planners_patterns))
]

unihelp/web/djangoproject/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>{% block title %} Base{% endblock %}</title>
    {% load static %}
    {% load fontawesome %}
    {% load bootstrap4 %}

    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/list.min.js' %}"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.22.2/moment.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/tempusdominus-bootstrap-4/5.0.1/js/tempusdominus-bootstrap-4.min.js"></script>
    {% fontawesome_stylesheet %}
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/tempusdominus-bootstrap-4.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    {{ form.media }}
</head>
<body>
    {% include "header.html" %}
    <main>
		<div class='container'>
		    {% block content %}
		    {% endblock %}
		</div>
	</main>
</body>
</html>

unihelp/web/djangoproject/templates/header.html
{% block header %}
{% load fontawesome %}
{% load template_tags %}
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand"  data-toggle="tooltip" data-placement="bottom" title="Click here to go to the main page." href="/"><font face="serif">UniHelp</font></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav">
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle {% if nav_bar == 'tasks' %}active{% endif %}"  href="#" id="navbarTasks" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">{% fontawesome_icon 'tasks' color='black' %} Tasks</a>
          <div class="dropdown-menu" aria-labelledby="navbarTasks">
            <a class="dropdown-item" data-toggle="tooltip" data-placement="bottom" title="Click here if you want to work on your tasks." href='{% url "unihelp:tasks" %}'>My</a>
            <a class="dropdown-item" data-toggle="tooltip" data-placement="bottom" title="Click here if you want to see the tasks available for reading." href='{% url "unihelp:can_read_tasks" %}'>Can read</a>
            <a class="dropdown-item" data-toggle="tooltip" data-placement="bottom" title="Click here if you want to see the tasks available for writing." href='{% url "unihelp:can_write_tasks" %}'>Can write</a>
            <a class="dropdown-item" data-toggle="tooltip" data-placement="bottom" title="Click here if you want to see how cool you are." href='{% url "unihelp:tasks_by_status" 3 %}'>Archive</a>
          </div>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle {% if nav_bar == 'notifications' %}active{% endif %}"  href="#" id="navbarNotifications" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">{% fontawesome_icon 'envelope outlined' color='black' %} Notifications</a>
          <div class="dropdown-menu" aria-labelledby="navbarNotifications">
            <a class="dropdown-item" data-toggle="tooltip" data-placement="bottom" title="Click here to work with all notifications." href='{% url "unihelp:all_notifications" %}'>All</a>
            <a class="dropdown-item" data-toggle="tooltip" data-placement="bottom" title="Click here to work with notifications by state CREATED." href='{% url "unihelp:created_notifications" %}'>Created</a>
            <a class="dropdown-item" data-toggle="tooltip" data-placement="bottom" title="Click here to work with notifications by state AWAIT." href='{% url "unihelp:await_notifications" %}'>Await</a>
            <a class="dropdown-item" data-toggle="tooltip" data-placement="bottom" title="Click here to work with notifications by state SHOWN." href='{% url "unihelp:shown_notifications" %}'>Shown</a>
          </div>
        </li>
        <li class="nav-item">
          <a class="nav-link {% if nav_bar == 'planners' %}active{% endif %}" data-toggle="tooltip" data-placement="bottom" title="Click here to work with planners." href="{% url 'unihelp:planners' %}">{% fontawesome_icon 'paperclip' color='black' %} Planners</a>
        </li>
        <li class="nav-item">
          <a class="nav-link {% if nav_bar == 'tags' %}active{% endif %}" data-toggle="tooltip" data-placement="bottom" title="Click here to work with tags." href='{% url "unihelp:tags" %}'>{% fontawesome_icon 'tag' color='black' %} Tags<span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
          <a class="nav-link {% if nav_bar == 'users' %}active{% endif %}" data-toggle="tooltip" data-placement="bottom" title="Click here to see users." href='{% url "unihelp:users" %}'>{% fontawesome_icon 'user' color='black' %} Users<span class="sr-only">(current)</span></a>
        </li>
      </ul>
      <ul class="navbar-nav mr-auto"></ul>
      {% if user.is_authenticated %}
        <ul class="navbar-nav ">
          <li class="nav-item dropdown">
            <a href="#" class="nav-link dropdown-toggle" id="navLinkNotifications" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">{{ await_notifications_count }} {% fontawesome_icon 'envelope outlined' color='black'%}</a>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navLinkNotifications">
              {% for notification in await_notifications %}
                <div class="dropdown-item background-gray">
                  <div class='notifications'>
                    <div class='notification'>
                      <div class='title inline'>
                        <h5>{{notification.title}}</h5>
                      </div>
                      {% if notification.task_id is not None %}
                      <div class='task inline margin-right'>
                        <a href="{% url 'unihelp:show_task' notification.task_id %}">
                          <h5>{% get_task_title notification.user_id notification.task_id %}</h5>
                        </a>
                      </div>
                      {% endif %}
                      <form style='display: inline-block;' action="{% url 'unihelp:set_shown_notification' notification.id %}" method='post'>
                        {% csrf_token %}
                        <button type='submit' data-toggle="tooltip" data-placement="bottom" title="You saw the notification! Click here." class='btn btn-dark'>Set shown</button>
                      </form>
                    </div>
                  </div>
                </div>
              {% empty %}
                <div class="dropdown-item">
                    <h5>No notifications</h5>
                </div>
              {% endfor %}
            </div>
          </li>
        </ul>
        <ul class="navbar-nav ">
          <li class="nav-item dropdown">
            <a href="#" class="nav-link dropdown-toggle" id="navLinkUser" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Profile</a>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navLinkUser">
              <div class="dropdown-item"  data-toggle="tooltip" data-placement="bottom" title="I'm think.. it's you!">{{user.username}}</div>
              <div class="dropdown-divider"></div>
              <a class="dropdown-item"  data-toggle="tooltip" data-placement="bottom" title="I'll miss..." href='{% url "unihelp:logout" %}'>Logout</a>
            </div>
          </li>
        </ul>
      {% else %}
        <a href='{% url "unihelp:login" %}' class='btn btn-dark mr-2'>Log In</a>
        <a href='{% url "unihelp:signup" %}' class='btn btn-outline-dark'>Sign Up</a>
      {% endif %}
    </div>
  </nav>
{% endblock %}

unihelp/web/djangoproject/templates/home.html
<!-- templates/home.html -->
{% extends 'base.html' %}

{% block title %}Home{% endblock %}

{% block content %}
  <div class='jumbotron'>
    {% if user.is_authenticated %}
    <h1 class='display-4'>Welcome, {{ username }}!</h1>
    {% else %}
      <h1 class='display-4'>You are not logged in.</h1>
      <a href="{% url 'unihelp:login' %}">Fix it!</a>
    {% endif %}
  </div>
{% endblock %}